# Datenstrom Yellow extension settings

Extension: Draft
Version: 1.0.1
Description: Support for draft pages.
Developer: Anna Svensson
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-draft/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-draft
DocumentationLanguage: en, de, sv
Published: 2026-09-25 19:06:45
Status: maintained
system/workers/draft.php: draft.php, create, update
